### ISSUE TITLE
Convert To Swift

### ISSUE THREAD

**Issue by jaredStef** [firebase/friendlypix#10]
I was going to make a fork of the iOS app and rewrite it in Swift. I just figured I'd post here before doing so incase there was any input or urge to recode it within this repo.

**Comment by yannsonnboys** [comment]
Great idea JaredStef just do it :)

**Comment by sky1234** [comment]
@jaredStef were you able to finish this rewrite in Swift? just checking.

**Comment by jaredStef** [comment]
@sky1234 I posted the issue in May and finally got the Ok in August. I'm really busy now on multiple projects, so I didn't get to it.
