### ISSUE TITLE
AngularJs request 

### ISSUE THREAD

**Issue by aguilalibreweb** [firebase/friendlypix#11]
Hey guys, thanks for sharing this awesome sample. I would like to know If there is any AngularJs implementation of this? I already looked at the web script but I was not able to figure it out how to use it in AngularJs. Any help with this is highly appreciated.

**Comment by dcontreras87** [comment]
Really guys, nobody else is interested in an AngularJs sample of this? :/

**Comment by ianbarber** [comment]
There isn't an Angular version of this sample - in part because right now the AngularFire bindings are still being update to the new SDK!

**Comment by jcyh0120** [comment]
I would like to see an angular version!!

**Comment by moplin** [comment]
I am really interested, I just read this.

**Comment by samtstern** [comment]
We're no longer maintaining the friendlypix-web sample so I am going to close this issue.  Thank you for your suggestion!
