### ISSUE TITLE
Want description of the Data Structure 

### ISSUE THREAD

**Issue by joshyipkato** [firebase/friendlypix#14]
I can't seem to have the iOS demo running, but I'm still interested to see the data structure
Can someone please post the structure of the JSON tree?

PS from just reading the code,
my guess is something like this:
![img_7639](https://cloud.githubusercontent.com/assets/17095241/15769554/be30b8fe-298e-11e6-88ad-faf87b660c89.JPG)

**Comment by nicolasgarnier** [comment]
To get an overview of the data structure the best right now is to look at the security rules file.

We'll be adding a section in the docs that describes the Data model, I'll update this bug once we have that.

**Comment by nicolasgarnier** [comment]
We have now added a [design.md](design.md) file in this repository with a description of the design.
