### ISSUE TITLE
android app feeds pagination

### ISSUE THREAD

**Issue by VihaanVerma89** [firebase/friendlypix#16]
Looking at the code it seems all the feed are fetched in one go. This will be problematic when there is lot of data to be fetched. The https://friendly-pix.com/ site is providing feed pagination. Should the Query class be used for pagination ?

**Comment by ishara** [comment]
Is any one working on it?

**Comment by patricknasc** [comment]
I noticed... What should be the best practices to solve this?

**Comment by gkaldev** [comment]
This issue was moved to firebase/friendlypix-android#26
