### ISSUE TITLE
Commit Message : Initial WIP commit to get code into VCS.

### ISSUE THREAD

**Issue by antonio-eggberg** [firebase/friendlypix#18]
Hi, 

For my local repo can I delete all the files from "Initial WIP commit to get code into VCS."? will it be ok? I just want to remove files that are not being used at all. 

thanks.

**Comment by nicolasgarnier** [comment]
Yes the blobserver directory is not used at this point you can remove it.

**Comment by nicolasgarnier** [comment]
Hey @gkaldevrel is it OK to delete the `blobserver` directory? Not sure what it's used for but it seems it;s not needed?

**Comment by gkaldevrel** [comment]
Yeah, it's safe to delete. I was just using it before we incorporated storage. I was going to delete it in my next commit, but feel free to do it earlier if you want.

**Comment by gkaldev** [comment]
This issue was moved to firebase/friendlypix-android#25
