### ISSUE TITLE
Image preview is inconsistent with result after uploading

### ISSUE THREAD

**Issue by 1j01** [firebase/friendlypix#19]
If you select a transparent image, it shows it on a white background. After uploading, you get an opaque image with a black background. For GIFs it shows the preview like animation is allowed, but it's not. If an image is uploaded that lacks an extension, the preview doesn't show up, but it does work when uploading. Finally, the sizing of the image is completely different in the preview (full image shown with it's native ratio) from the resulting card when uploaded (fills available fixed area, usually cutting some off).

**Comment by 1j01** [comment]
![i made a transparent version of dat boi cropped](https://cloud.githubusercontent.com/assets/3630663/16466331/ae5b15dc-3e10-11e6-8535-598c2cbe9bad.gif)

**Comment by nicolasgarnier** [comment]
Yes I confirm we should fix this and have a preview that's what the final result will look like. Thanks for reporting

**Comment by nicolasgarnier** [comment]
This issue was moved to firebase/friendlypix-web#19
