### ISSUE TITLE
Posts sometimes show wrong image or no image

### ISSUE THREAD

**Issue by 1j01** [firebase/friendlypix#20]
If you've uploaded an image, errant posts will show that image until you refresh the page, at which point it won't show any image. Clicking to view the full image works.

e.g.
* https://friendly-pix.com/post/-KLO-heSOLsDaMphet6J
* https://friendly-pix.com/post/-KKI82R9A_zZpE7NoerZ

**Comment by nicolasgarnier** [comment]
This is happening because some image file names contained parenthesis characters `(` and `)` which I am not escaping correctly. Will fix that soon!
