### ISSUE TITLE
Wrong post pictures

### ISSUE THREAD

**Issue by niyikush** [firebase/friendlypix#21]
my uploaded picture appears on someone else's postline
![capture1](https://cloud.githubusercontent.com/assets/20197285/16437870/405da7c0-3da2-11e6-8571-ef74b1af1b37.JPG)
![capture2](https://cloud.githubusercontent.com/assets/20197285/16437875/4aead44c-3da2-11e6-81c8-236629570583.JPG)

**Comment by nicolasgarnier** [comment]
This is caused by an issue where some image file names contained parenthesis characters `(` and `)` which I am not escapting correctly. Will follow up on #20
