### ISSUE TITLE
Sign in with Google Button not displaying

### ISSUE THREAD

**Issue by Fisch201** [firebase/friendlypix#22]
After I deployed the app - mine doesnt show the button to Login w/ Google.   

Did I miss a step?

**Comment by nicolasgarnier** [comment]
You should see it. Can you share the URL to which you've deployed so we can have a look? If you only tested on `localhost` can you make sure you went through all steps that are in the README? do you see any errors in the JS console?

**Comment by Fisch201** [comment]
Here's where I deployed to hosting. 

https://mbci-gcm.firebaseapp.com/

**Comment by nicolasgarnier** [comment]
It seems that none of the `.js` files have been deployed. Can you make sure tu run `npm run build` before deploying?

**Comment by tameravci** [comment]
I have the same issue. Even when I host it locally I don't see the google sign-in button. When I run `npm run build` I get:

> @ build /home/tameravci/Desktop/friendlypix/web
> babel scripts -s --minified --compact true -d lib; bower install; echo 'Done. Ready to deploy.'

Error: Cannot find module 'core-js/library/fn/get-iterator'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/tameravci/Desktop/friendlypix/web/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-template-literals/node_modules/babel-runtime/core-js/get-iterator.js:1:93)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
Done. Ready to deploy.

**Comment by abelcd** [comment]
I have exactly the same problem... :(

**Comment by nicolasgarnier** [comment]
@tameravci can you try running `npm i core-js --save` as described at the end of https://github.com/babel/gulp-babel/issues/52

@abelcd Are you facing the same issue as @tameravci ?

**Comment by abelcd** [comment]
This is what I get: 

![image](https://cloud.githubusercontent.com/assets/19714748/17024085/5e5cd210-4f4e-11e6-8ee5-0028eda88a0a.png)

**Comment by nicolasgarnier** [comment]
Can you try what I said above? Did you try running `npm run build` to see if you get any errors?

**Comment by nicolasgarnier** [comment]
(Just saw that you said you already ran `npm run build`).

Was there any errors in the console from running npm run build? What happens here is that the JS files did not get generated so the HTML file is served instead (because it's a single page app and the index.html is served for any URL that's not another file).

Basically can you check that you had the JS files generated in `/lib` ? You should see:

![image](https://cloud.githubusercontent.com/assets/3766663/17025214/3d34a4e8-4f5b-11e6-8af3-eb5eabb3bf8a.png)

**Comment by abelcd** [comment]
Hi Nicolas,

I figured out the issues: the JS files where in a folder named 'scripts' so I changed it to 'lib' and it started to work. I also had to enable google as an auth provider in the firebase console.

Thnaks a lot!
Abel

**Comment by nicolasgarnier** [comment]
The JS files in `scripts` are written in ES2015 so this will only work in newer browsers (like Chrome) I'm not even sure they will work completely in Firefox and it won't work in Safari, IE etc...

What `npm run build` and `npm run serve` do is that they transpile these ES2015 JS files (that are in `scripts`) into ES5 ("normal"/older Javascript) into `lib` folder that works on every browsers.

**Comment by morgs32** [comment]
I had this issue and the problem was that bower install was putting my components in `app/bower_components`, so I created a `.bowerrc` file with contents ```
{ "directory": "./bower_components" }
```
and now it finds my lib files alright.

**Comment by morgs32** [comment]
But, I still don't see the login button just "skip sign in" and I can go to the feed page

**Comment by nicolasgarnier** [comment]
Thanks for the tip @morgs32 I'll add this file to the repo!

**Comment by IMJONEZZ** [comment]
I have this issue again now. No errors running npm run build. I'm also getting the error, where if I force a sign-in through the network, I get a 404 Not Found page instead of the feed.
