### ISSUE TITLE
Versão web

### ISSUE THREAD

**Issue by johnendz** [firebase/friendlypix#24]
page.js:1 Uncaught SyntaxError: Unexpected token <
jquery.min.js:1 Uncaught SyntaxError: Unexpected token <
latinize.js:1 Uncaught SyntaxError: Unexpected token <
sweetalert.min.js:1 Uncaught SyntaxError: Unexpected token <
auth.js:42Uncaught ReferenceError: $ is not defined_class @ auth.js:42(anonymous function) @ auth.js:96
search.js:48Uncaught ReferenceError: $ is not defined_class @ search.js:48(anonymous function) @ search.js:104
uploader.js:57Uncaught ReferenceError: $ is not defined_class @ uploader.js:57(anonymous function) @ uploader.js:263
userpage.js:34Uncaught ReferenceError: $ is not defined_class @ userpage.js:34(anonymous function) @ userpage.js:284
post.js:37Uncaught ReferenceError: $ is not defined_class @ post.js:37(anonymous function) @ post.js:365
feed.js:38Uncaught ReferenceError: $ is not defined_class @ feed.js:38(anonymous function) @ feed.js:238
routing.js:30Uncaught ReferenceError: $ is not defined_class @ routing.js:30(anonymous function) @ routing.js:142
material.min.js:1 Uncaught SyntaxError: Unexpected token <

##### não consigo resolver problema :/

**Comment by nicolasgarnier** [comment]
@johnendz Could you: Make sure you go through all steps described in the README to setup the project. Also could you deploy the sample online (with `firebase deploy`) so I could see what's wrong?

**Comment by nicolasgarnier** [comment]
Let's follow up on the same issue on #22
