### ISSUE TITLE
Error Building iOS Project

### ISSUE THREAD

**Issue by gregk8288** [firebase/friendlypix#25]
The app is throwing the following error when I try and build either in the simulator or on the actual device. Can someone please point me in the right direction. Thanks. 

`ibtool --reference-external-strings-file --errors --warnings --notices --minimum-deployment-target 7.0 --output-format human-readable-text --compile /Users/gregkockott/Library/Developer/Xcode/DerivedData/FriendlyPix-cokdbrzofvrkvcepjjnzxixrkvpj/Build/Products/Debug-iphonesimulator/FriendlyPix.app/STXUserActionCell.nib /Users/gregkockott/www/friendlypix/ios/Pods/STXDynamicTableView/STXDynamicTableView/Cells/STXUserActionCell.xib --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platf/Users/gregkockott/www/friendlypix/ios/Pods/Target Support Files/Pods-FriendlyPix/Pods-FriendlyPix-resources.sh: line 51: echo: write error: Resource temporarily unavailable
Command /bin/sh failed with exit code 1
`

**Comment by barulopez** [comment]
+1 same issue, any updates? @gregk8288 did you find a solution to this?

**Comment by tredds** [comment]
hey, check this http://stackoverflow.com/a/35441556/1169171. looks like restarting your mac does the trick. is there a zombie process hanging around?

**Comment by iulukaya** [comment]
You may also try cleaning your build folder in xcode. From xcode, under product tab, hit option button, that selection will open up.

**Comment by iTA9178** [comment]
+1 same issue.
