### ISSUE TITLE
Home fragment not working for android?

### ISSUE THREAD

**Issue by asbadve** [firebase/friendlypix#26]
It shows nothing all other parts are working except Home fragment for android sample.

**Comment by Divala** [comment]
Facing the same problem. Anyone to help?

**Comment by patricknasc** [comment]
I will code this for us!

**Comment by Divala** [comment]
Okay thanks

**Comment by migueltarga** [comment]
#65

**Comment by v3dinc** [comment]
1.

**Comment by gkaldev** [comment]
This issue was moved to firebase/friendlypix-android#24
