### ISSUE TITLE
Android failed to upload 

### ISSUE THREAD

**Issue by stevealbertwong** [firebase/friendlypix#29]
i keep having could not create upload task when try to upload for both home and feed tab.

**Comment by stevealbertwong** [comment]
also in post fragment there is a couple of TODO task, the FirebaseRecyclerAdapter code does not seem have finished?

**Comment by patricknasc** [comment]
The upload recently is working fine. If you're still having this issue, probably your Firebase project isn't configured properly. How are your Storage rules? It shoud be something like this:

`service firebase.storage {
  match /b/friendlypix-XPTO.appspot.com/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
  }
}
`

**Comment by gkaldev** [comment]
This issue was moved to firebase/friendlypix-android#22
