### ISSUE TITLE
IOS App - Warnings

### ISSUE THREAD

**Issue by giovannicoco** [firebase/friendlypix#3]
@iulukaya  got 11 warnings in my Xcode 7.3.

1. Repo cloned
2. Ran 'pod install'
3. Changed Deployment Target to 8.0 on Project and Targets
4. Inserted GoogleService-Info.plist to root directory
5. Inserted GoogleService-Info.plist to all Target
6. Inserted URL Types on Targets-->Info-->URL Types-->URL Schemes (Google SignIn)

I am doing something wrong?

![captura de tela 2016-05-22 as 08 26 36](https://cloud.githubusercontent.com/assets/6585496/15453735/00b0dcbe-1ff7-11e6-8a3c-15448eeb5dd6.png)
![captura de tela 2016-05-22 as 08 28 43](https://cloud.githubusercontent.com/assets/6585496/15453744/3e5d79a0-1ff7-11e6-9f06-ce2de742ec6c.png)

Thanks

**Comment by iulukaya** [comment]
Can you post warnings?

**Comment by iulukaya** [comment]
No, they are fine, they won't affect functionality but I'll update code to eliminate them. Cheers,
