### ISSUE TITLE
How do I make authentication appear with this example code for web?

### ISSUE THREAD

**Issue by patelneel1994** [firebase/friendlypix#31]
I don't really want to include Google or Facebook sign in. I just wanted to test it with "skip sign in", but it didn't show. Since I don't want to set up Google and Facebook sign in I am not updating the stuff that I have to do with those two. Is there anything I have to do to make "skip sign in" appear? I deployed it locally and tried to access http://localhost:5000/feed but didn't work.

**Comment by nicolasgarnier** [comment]
hey @patelneel1994 Do you have any errors in the JS Console? What steps have you skipped? FYI you should just have skipped Step 2 and 3 of **Create Firebase Project** in the [README.md](../tree/master/web/README.md)

**Comment by patelneel1994** [comment]
Thank you for quick reply @nicolasgarnier I did skip step 2 and 3. I basically copied the header what was provided in Firebase console for web version and put it in index.html and then deployed it. It does deploy with security and storage rules. When I open the given hosted link it works fine. It opens up the page, but it doesn't have those sign in link! I can provide screenshot if you like!

**Comment by nicolasgarnier** [comment]
Ok it seeems the error happened because the scripts did not compile. Before deploying can you make sure you ran 'npm run build' ?

**Comment by nicolasgarnier** [comment]
You can refer to this issue: https://github.com/firebase/friendlypix/issues/22

**Comment by patelneel1994** [comment]
Thank you for your help. :D

**Comment by nicolasgarnier** [comment]
Have you ran `npm install` ? This should make sure that `babel` is installed.

**Comment by patelneel1994** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/6612313/17814244/85c6077e-65f4-11e6-832c-320d197bd12c.png)
