### ISSUE TITLE
Web - picUploadTask is an uncaught promise/ not a function

### ISSUE THREAD

**Issue by tomtom215** [firebase/friendlypix#33]
in Firebase.js line 430

```javascript
    var picUploadTask = picRef.put(pic, metadata).then(snapshot => {
      console.log('New pic uploaded. Size:', snapshot.totalBytes, 'bytes.');
      var url = snapshot.metadata.downloadURLs[0];
      console.log('File available at', url);
      return url;
    }).catch(error => {
      console.error('Error while uploading new pic', error);
    });
```

**Comment by nicolasgarnier** [comment]
@tomtom215 I'm sorry I don't see what the issue is. Could you explain a bit more?

**Comment by tomtom215** [comment]
I believe this had to do with being logged in to my Firebase-cli tools and referencing another project and there was something hung up there (as odd as that sounds).

I just downloaded the zip again, created a new Firebase app and set up the web project and all seems well! Thanks for your quick response!

**Comment by nicolasgarnier** [comment]
Cool, I'm glad things worked out for you!
