### ISSUE TITLE
Web - npm run serve does not start local Firebase server

### ISSUE THREAD

**Issue by tomtom215** [firebase/friendlypix#34]
In the readme, it says to start a local server to run in development by running "npm run serve" however it does not appear to run the "serve" script correctly from package.json

current script in package.json for npm run is: 
"serve": "bower install; firebase serve & babel -w scripts -s --retain-lines -d lib"}

It seems to be missing bower arguments, skips creating the local firebase server and then compiles the scripts with babel and then stalls from there. Browsing to localhost:5000 shows that nothing is being served.

![image](https://cloud.githubusercontent.com/assets/4908716/17948112/67608a20-6a1d-11e6-8b34-16916bba75bb.png)

However, if you have all of the bower components installed/updated beforehand and run "firebase serve" in the directory it seems to work just fine:

![image](https://cloud.githubusercontent.com/assets/4908716/17948207/d49319e6-6a1d-11e6-8d63-0ce1927f5335.png)

**Comment by nicolasgarnier** [comment]
Hey @tomtom215

All the script does is run 'bower install' first. Does that not work for you if you simply run 'bower install' from the command line manually? 
Could you tell me what your environment is? (Linux, macos...) ? I'll try to reproduce.

**Comment by tomtom215** [comment]
Running Win10. 
If this script was only mean to run bower install, I did this manually when I felt that the run serve wasn't doing the trick and all was well, so feel free to close this issue if you feel it was normal behavior. 

PS- I had also changed/ un-commented to use the ES2015 scripts instead of ES5 so I wasn't sure if that was contributing to the build/ serve "issue" I was experiencing.

**Comment by nicolasgarnier** [comment]
Ah yes, we have an open issue on Windows with this command. See #4 I think in this case `bower install` is taking the rest of the line as arguments (so it thinks `firebase serve` is an argument of the bower command) and also `&` isn't working. I still need to fix it. I'll close in favor of #4. I'll add a note on the readme in the mean time :)
