### ISSUE TITLE
Storage rules now returning error on Firebase Deployment 

### ISSUE THREAD

**Issue by tomtom215** [firebase/friendlypix#36]
Did Firebase/ Storage change the rules namespace/ am I missing something here?

I made some changes to the front-end and when deploying to firebase I received this error which hasn't come up before today:

![image](https://cloud.githubusercontent.com/assets/4908716/18457244/08f44e56-7925-11e6-8c45-2c4e21f51bcd.png)

I double checked my rules, and they remain the untouched besides the addition of my storage bucket and they look the same as the Master on the Web repo

![image](https://cloud.githubusercontent.com/assets/4908716/18457272/496d1e7c-7925-11e6-9008-22be9d7e508d.png)

Rules can be found at - ./friendlypix/web/storage.rules

**Comment by nicolasgarnier** [comment]
Fixed! sorry about that. `timestamp` is now a reserved keyword in storage security rules.
