### ISSUE TITLE
[Urgent] Xcode doesn't build 

### ISSUE THREAD

**Issue by alonbee** [firebase/friendlypix#39]
I cloned the whole file & try to build the iOS app in Xcode(8.0). But there are parsing issues even if I updated the pod. Does anyone know  how to resolve this issue ?
![screen shot 2016-10-05 at 1 08 31 am](https://cloud.githubusercontent.com/assets/12573192/19117044/a258ff5c-8ae5-11e6-991f-2e7cb53edac6.png)

**Comment by DroiSystem** [comment]
try $pod install

**Comment by AZsoftAlanZheng** [comment]
try "$pod install" at friendlypix/ios

**Comment by alonbee** [comment]
pod install did solve part of the erros. But there are unknown errors I still cannot solve, is that because of the pod version or Xcode version. I am using the latest one. 
![fail](https://cloud.githubusercontent.com/assets/12573192/19178243/ec933a6c-8c1e-11e6-8715-53889fbb8e23.png)

**Comment by alonbee** [comment]
@AZsoftAlanZheng

**Comment by mcBontempi** [comment]
yep for me i get all sorts of errors, id suggest that you take a look as there were quite a few.

**Comment by alonbee** [comment]
Looking forward to your updates ! Thank you !!

**Comment by alonbee** [comment]
@AZsoftAlanZheng  @mcBontempi

**Comment by iulukaya** [comment]
Code wasn't updated for FirebaseUI 1.0. I'll be updating it shortly, in the meantime I updated the Podfile to point back to legacy version.

**Comment by iulukaya** [comment]
Master branch is updated with FirebaseUI 1.0 support. Let me know if you get any problems. Cheers
