### ISSUE TITLE
npm serve broken on windows

### ISSUE THREAD

**Issue by lxnyce** [firebase/friendlypix#4]
The following command doesn't work in windows CLI.

"serve": "bower install; firebase serve & babel -w scripts -s --retain-lines -d lib"

See here for some more info : http://stackoverflow.com/questions/30950032/how-can-i-run-multiple-npm-scripts-in-parallel

**Comment by tomtom215** [comment]
Here is my work around for package.son for those on windows experiencing errors. I left the original ones in for easy comparison. Just run Bower install manually and then win* scripts will work the same as the originals.


{
  "scripts": {
    "build": "babel scripts -s --minified --compact true -d lib; bower install; echo 'Done. Ready to deploy.'",
    "win-build": "babel scripts -s --minified --compact true -d lib",
    "serve": "firebase serve & babel -w scripts -s --retain-lines -d lib",
    "win-serve":"firebase serve && babel -w scripts -s --retain-lines -d lib"
  },

**Comment by llanzo** [comment]
Thanks for package.json workaround, for anyone else who ends up here, make sure to double check the scripts path.  Following the example provided by @tomtom215 I modified my package.json on windows as follows  :
{
  "scripts": {
    "build": "**babel public/scripts** -s --minified --compact true -d public/scripts-es5; bower install; echo 'Done. Ready to deploy.'",
    "win-build": "**babel public/scripts** -s --minified --compact true -d lib",
    "serve": "bower install; firebase serve & babel -w public/scripts -s --retain-lines -d public/scripts-es5",
    "win-serve":"firebase serve && babel -w scripts -s --retain-lines -d lib"
  },

**Comment by nicolasgarnier** [comment]
This issue was moved to firebase/friendlypix-web#16
