### ISSUE TITLE
Weak write rule for posts

### ISSUE THREAD

**Issue by MicheleBertoli** [firebase/friendlypix#42]
I was looking for an example of a rule where only authors could write on a path, and I found this:
```
"posts": {
  ".read": true,
  "$postId": {
    ".write": "(auth.uid === newData.child('author').child('uid').val()) || (!newData.exists() && auth.uid === data.child('author').child('uid').val())" // Allow Writes and deletes
  }
},
```

As the comment says, it actually allows writes and deletes.
However, the way the rule checks if the `author/uid` is the same as the current `auth.id` allows any author to override other author's posts.
In fact, the rule only validates that the `newData` contains the authenticated user id but it ignores the current value (`data`).

As a result, I can assign other people's posts to myself using the console:
`firebase.database().ref('/posts/POST_ID').update({ author: { uid: 'MY_AUTH_UID' } })`

A stronger rule would be:
```
".write": "(newData.exists() && auth.uid === newData.child('author').child('uid').val() || !newData.exists()) && (data.exists() && auth.uid === data.child('author').child('uid').val() || !data.exists())",
```

It checks `newData` (create, update) and `data` as well (update, delete).

**Comment by nicolasgarnier** [comment]
Thanks @MicheleBertoli good catch. I'll make the changes :)
