### ISSUE TITLE
iOS Won't Build...   Missing Files?

### ISSUE THREAD

**Issue by AvonGroveDynaMOE** [firebase/friendlypix#44]
I keep getting this error?

error: unable to read module map contents from 'Target Support Files/UALogger/UALogger.modulemap': Error Domain=NSCocoaErrorDomain Code=260 "The file “UALogger.modulemap” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/jdambrosio/Downloads/friendlypix-master/ios/Pods/Target Support Files/UALogger/UALogger.modulemap, NSUnderlyingError=0x7fadd2d66f50 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by AvonGroveDynaMOE** [comment]
Just ran a pod Update and now get this error:

/Users/jdambrosio/Downloads/friendlypix-master/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/FBSDKApplicationDelegate.m:250:42: No visible @interface for 'UIApplication' declares the selector 'openURL:options:completionHandler:'

**Comment by iulukaya** [comment]
Which vesion of sdk and device, are you trying to run it?

**Comment by AvonGroveDynaMOE** [comment]
Latest version of Xcode and building for iPhone 6 simulator.

**Comment by ToddKerpelman** [comment]
Hmm... I just grabbed the latest and I'm also getting an  error, although mine is around "Module 'Fabric' not found" Looks like maybe this library doesn't get added to the Podfile?

**Comment by AvonGroveDynaMOE** [comment]
@ToddKerpelman At first I was getting the Fabric issue too,  I removed it hoping it would build  but that just gave me more errors. Looks like you found a fix that I can try when I get home later...  Just wondering, what Xcode version are you using and what are you building it to?

**Comment by AvonGroveDynaMOE** [comment]
@iulukaya   @ToddKerpelman 

 What and in Which file do I need to change so that the app links to my firebase project?  I couldn't find a readme that had that information...

**Comment by ToddKerpelman** [comment]
@AvonGroveDynaMOE  You basically want to follow the steps for "Add Firebase for your App" listed [here](https://firebase.google.com/docs/ios/setup#add_firebase_to_your_app). You're going to add Firebase to your console, then drag the GoogleServices plist file into your project.

That said, if this is your first time with Firebase, maybe start off with one of the [Quickstart samples](https://github.com/firebase/quickstart-ios). Each of those is little simpler and easier to follow along with than this uber-sample.

**Comment by ToddKerpelman** [comment]
@iulukaya Make sure you remove the FirebaseUI version number from the podfile, and that'll fix the problem I encountered.

**Comment by AvonGroveDynaMOE** [comment]
@ToddKerpelman 
Ah so its just adding the plist that's generated?  The previous firebase app I worked on required a change in the actual code, but that was Swift so i assume that its different here and I don't need to worry about it?

Thanks again so much for the help!

**Comment by AvonGroveDynaMOE** [comment]
@ToddKerpelman @iulukaya 

 Okay so I got it working, now Xcode throws the following error 

"No visible @interface for 'UIApplication' declares the selector 'openURL:options:completionHandler:'"

It Highlights the following line:

 [[UIApplication sharedApplication] openURL:url options:@{} completionHandler:handler];

**Comment by ToddKerpelman** [comment]
@AvonGroveDynaMOE That seems to be a line from the Facebook SDK, so you might want to ping there as well, but it seems to me that it's trying to make an iOS 10 call from a device that doesn't support iOS 10 (which is odd, because the Facebook library looks like it should check for that.)

Can you confirm that your BaseSDK in your xcode project is listed as ios 10? And what version of Xcode are you running?

**Comment by AvonGroveDynaMOE** [comment]
@ToddKerpelman   Sure!  It's V 2.3.1... I'm now updating to Xcode 8.2.

**Comment by AvonGroveDynaMOE** [comment]
@ToddKerpelman 

Okay so now here is what i'm looking at now, i updated to Xcode 8.2, I had gotten a twitter kit error but I updated the target from iOS 7 to iOS 10.  Now I can build the app, but it opens to the launch screen and then throws a SIGABRT.  Below is my thread error:



objc[43231]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11e3b5998) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x11e134880). One of the two will be used. Which one is undefined.
2016-12-17 09:51:04.789 FriendlyPix[43231:5350159] Firebase automatic screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO in the Info.plist
2016-12-17 09:51:04.854: <FIRInstanceID/WARNING> FIRInstanceID AppDelegate proxy enabled, will swizzle app delegate remote notification handlers. To disable add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
2016-12-17 09:51:04.854: <FIRInstanceID/WARNING> Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"
2016-12-17 09:51:04.857 FriendlyPix[43231:5350159] *** Terminating app due to uncaught exception 'com.firebase.appinvite', reason: 'Firebase Invites has stopped your project due to a misconfiguration in your project that may prevent your app from behaving as expected:

Error: URL scheme needed for Google Sign-In not included in your app's Info.plist. Please refer to the Google Sign-In SDK documentation for more information.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000115d8dd4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001157ef21e objc_exception_throw + 48
	2   CoreFoundation                      0x0000000115df72b5 +[NSException raise:format:] + 197
	3   FriendlyPix                         0x000000010e75fda5 -[GINInvite(FIRApp) configureAppInvite:] + 1300
	4   FriendlyPix                         0x000000010e75f862 +[GINInvite(FIRApp) receivedReadyToConfigureNotification:] + 154
	5   CoreFoundation                      0x0000000115d2b5ec __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	6   CoreFoundation                      0x0000000115d2b4eb _CFXRegistrationPost + 427
	7   CoreFoundation                      0x0000000115d2b252 ___CFXNotificationPost_block_invoke + 50
	8   CoreFoundation                      0x0000000115cee282 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 2018
	9   CoreFoundation                      0x0000000115ced31b _CFXNotificationPost + 667
	10  Foundation                          0x00000001117c181b -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	11  FriendlyPix                         0x000000010e693500 +[FIRApp sendNotificationsToSDKs:] + 296
	12  FriendlyPix                         0x000000010e69233e +[FIRApp configureDefaultAppWithOptions:sendingNotifications:] + 341
	13  FriendlyPix                         0x000000010e69203a +[FIRApp configure] + 302
	14  FriendlyPix                         0x000000010e607c2c -[AppDelegate application:didFinishLaunchingWithOptions:] + 236
	15  UIKit                               0x00000001130103c2 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 290
	16  UIKit                               0x0000000113011d47 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4236
	17  UIKit                               0x00000001130180ed -[UIApplication _runWithMainScene:transitionContext:completion:] + 1731
	18  UIKit                               0x000000011301526d -[UIApplication workspaceDidEndTransaction:] + 188
	19  FrontBoardServices                  0x0000000117cfd6cb __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	20  FrontBoardServices                  0x0000000117cfd544 -[FBSSerialQueue _performNext] + 189
	21  FrontBoardServices                  0x0000000117cfd8cd -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	22  CoreFoundation                      0x0000000115d32761 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	23  CoreFoundation                      0x0000000115d1798c __CFRunLoopDoSources0 + 556
	24  CoreFoundation                      0x0000000115d16e76 __CFRunLoopRun + 918
	25  CoreFoundation                      0x0000000115d16884 CFRunLoopRunSpecific + 420
	26  UIKit                               0x0000000113013aea -[UIApplication _run] + 434
	27  UIKit                               0x0000000113019c68 UIApplicationMain + 159
	28  FriendlyPix                         0x000000010e60e7ef main + 111
	29  libdyld.dylib                       0x00000001164ec68d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by ashleyconnor** [comment]
You need to add the URL scheme like so:

![Here](https://www.dropbox.com/s/wubv0q9slr1mu78/Screenshot%202016-12-26%2017.50.19.png?dl=1)

You get that from your `GoogleService-Info.plist` under `REVERSED_CLIENT_ID`

**Comment by yofu1234** [comment]
I'm getting the same error. 
`Error: URL scheme needed for Google Sign-In not included in your app's Info.plist. Please refer to the Google Sign-In SDK documentation for more information.'`

But it's already in there.
![image](http://content.screencast.com/users/yofu1234/folders/Jing/media/99b1f29e-8bc2-4e77-96f4-f77bd58feefa/00000001.png)
Also I suppose to place GoogleService-Info.plist in root or under Supporting Files folder like with the Info.plist cuz I tried both?

**Comment by AvonGroveDynaMOE** [comment]
@yofu1234 Oh I had the same issue... in your pod file, remove the version number so just "Firebase SDK" is there.. run pod update and you should be good

**Comment by ashleyconnor** [comment]
@yofu1234 you need to add another entry with the value from GoogleSevice-Info.plist

**Comment by ToddKerpelman** [comment]
@yofu1234 You don't want to literally include the string REVERSED_CLIENT_ID -- that's intended to be a placeholder. Instead, you want to use the value of the reversed client id in your info.plist file. That'll be something like "com.googleusercontent.apps.4739234012-4asldqperaldqwerqsiy29384". 

(The same thing will apply to the Facebook and Twitter URL schemes if you want to support sign-in from those providers)
