### ISSUE TITLE
[ANDROID] Bug in current's user User Detail screen when clicking follow/unfollow.

### ISSUE THREAD

**Issue by patricknasc** [firebase/friendlypix#49]
Bug in current's user User Detail screen when taping follow/unfollow button. For some reason, if a user visits his own User Detail screen, whenever he toggles the follow/unfollow button the ImageViews containing his posts will duplicate.

**Comment by migueltarga** [comment]
#67 should fix this.

**Comment by gkaldev** [comment]
This issue was moved to firebase/friendlypix-android#19
