### ISSUE TITLE
[ANDROID] The user detail way to display user's post isn't neat

### ISSUE THREAD

**Issue by patricknasc** [firebase/friendlypix#59]
Comparing the web version with the android version, it's pretty clear that this feature besides not being properly finished, it's not neat enough. Maybe using a 3 columns grid or even a linear vertical recycler view should be much more good looking than the way it is now. Should we improve it?

Web version: 
![screen shot 2016-12-20 at 07 05 03](https://cloud.githubusercontent.com/assets/784621/21344396/c026dbfc-c682-11e6-9618-4556f621ddd3.png)

Android version:
![screenshot_20161220-070239](https://cloud.githubusercontent.com/assets/784621/21344481/177e3df0-c683-11e6-9a0e-ecaddb252337.png)

**Comment by gkaldev** [comment]
This issue was moved to firebase/friendlypix-android#13
