### ISSUE TITLE
[ANDROID] Menu Item Profile within menu_feeds.xml not displaying user's profile picture.

### ISSUE THREAD

**Issue by patricknasc** [firebase/friendlypix#60]
I guess it was expected that this menu item should also display the user's profile. I think that menu items doesn't allow to customize the icon format, so that probably it won't be possible to repeat the circle format for profile pictures that are being used throughout the app. The options I see are: 

1) Use a square format profile picture and keep using a menu item.
2) Change the menu item for a ImageView/CircleImageView.

**Comment by gkaldev** [comment]
This issue was moved to firebase/friendlypix-android#12
