### ISSUE TITLE
Nougat not posting image

### ISSUE THREAD

**Issue by Sitarman** [firebase/friendlypix#71]
Hello, I have tested Friendlypix on lollipop and marshmallow and works fine posting images but on my nexus 5x nougat 7.1.1  I get a , 'couldn't resize bitmap' error.

**Comment by oktay-sen** [comment]
Same here. With no changes to the codebase, taking a picture or selecting from gallery both cause this error. I'm using OnePlus 3 with Nougat 7.0

**Comment by yofu1234** [comment]
Check this PR: https://github.com/firebase/friendlypix/pull/57 for the fix.

**Comment by gkaldev** [comment]
This issue was moved to firebase/friendlypix-android#11
