### ISSUE TITLE
NPM Deprecated: node-uuid@1.4.7

### ISSUE THREAD

**Issue by tomtom215** [firebase/friendlypix#73]
Suggested: to use the uuid module instead

As I am not sure/haven't traced the usage extent of this dependency in friendlypix/web I wanted to post an issue to make the developers aware (I'm sure you are) in case this deprecated package could pose a large issue.

**Comment by nicolasgarnier** [comment]
Thanks @tomtom215, I updated the google-cloud dependencies in https://github.com/firebase/friendlypix-web/commit/8304bfee02dd502b148823a525531be443bbc01e and am no longer seeig this.
