### ISSUE TITLE
File upload consistently failing

### ISSUE THREAD

**Issue by STandQdotcom** [firebase/friendlypix#76]
URL: https://friendly-pix.com/

Not able to upload any file since last 24 hrs. Upload fails with following messages on console:

Error while uploading new pic (firebase.js:142)
code: "storage/unauthorized"

**Comment by nicolasgarnier** [comment]
Thanks so much for the report @STandQdotcom ! Looks like a backend change in Firebase Storage broke something. We're rolling back the change.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (118/100 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:32940 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWo6e-003otz-HD
	for greg@biomassiv.es; Thu, 26 Jan 2017 11:45:08 -0600
Date: Tue, 24 Jan 2017 14:58:29 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485298709;
	bh=/Las6xJbTWz8wvKsxiNgS896ktBgDXaAyxghK6mnDis=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=UR1nFA0eJpdsTpxkEo9jrsAs1UXT45nhaOArPD7w8ZShkg8XbqdICtBaf+PX3/TqT
	 VIpId3aRk6RwqLGpZ+Oo34MHg9P4zk4eDqdDDgQ1W6TIGRKRdQ409f8tgSBk+9Xzhg
	 C3ZHjqW0xluMYhYAQQH+znoQY8ezmzje//3JBFQM=
