### ISSUE TITLE
App crashes after submit button pressed.

### ISSUE THREAD

**Issue by shubham-git** [firebase/friendlypix#80]
java.lang.RuntimeException: An error occurred while executing doInBackground()

at com.google.android.gms.common.internal.zzab.zzb(Unknown Source)
 at com.google.firebase.storage.StorageReference.child(Unknown Source)

on
 final StorageReference fullSizeRef = photoRef.child(FirebaseUtil.getCurrentUserId()).child("full").child(timestamp.toString()).child(fileName + ".jpg");
            final StorageReference thumbnailRef = photoRef.child(FirebaseUtil.getCurrentUserId()).child("thumb").child(timestamp.toString()).child(fileName + ".jpg");

**Comment by yofu1234** [comment]
Check this PR: https://github.com/firebase/friendlypix/pull/57 for the fix.

**Comment by nicolasgarnier** [comment]
@gkaldevrel Could you have a look at this? There seem to be a PR that fixes the issue (thx @yofu1234).
