### ISSUE TITLE
Couldn't resize bitmap

### ISSUE THREAD

**Issue by michaeldovoh** [firebase/friendlypix#81]
AM USING NOKIA X. AND IT TELL ME Couldn't resize bitmap. ANY HELP PLEASE. I TRIED CHANGING THE RESOLUTION BUT STILL

**Comment by yofu1234** [comment]
Check this PR: https://github.com/firebase/friendlypix/pull/57

**Comment by nicolasgarnier** [comment]
@gkaldevrel Could you have a look at this? There seem to be a PR that fixes the issue (thx @yofu1234).

**Comment by shukerullah** [comment]
Its working on real device but not on emulator.

**Comment by gkaldev** [comment]
This issue was moved to firebase/friendlypix-android#8
