### ISSUE TITLE
unable to cache image 

### ISSUE THREAD

**Issue by michaeldovoh** [firebase/friendlypix#82]

**Comment by morganchen12** [comment]
Please add a description, then reopen this issue.

**Comment by michaeldovoh** [comment]
all the posts disappear when the user leaves the feedactivity to the profile  and have to fetch whenever user goes to the feedactivity

**Comment by michaeldovoh** [comment]
all the posts disappear when the user leaves the feedactivity to the profile  and have to fetch whenever user goes to the feedactivity

**Comment by morganchen12** [comment]
Is this an issue on iOS, Android, or web?

**Comment by michaeldovoh** [comment]
android please.

**Comment by gkaldev** [comment]
This issue was moved to firebase/friendlypix-android#7
