### ISSUE TITLE
[iOS] Crash: Post Sign-In

### ISSUE THREAD

**Issue by joeydambrosio** [firebase/friendlypix#84]
Below is the debug code I get,  I get a Thread 1: SIGABRT on the line of code at the very bottom.

`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid condition not satisfying: [arrayOrDictionary isKindOfClass:NSArray.class] || [arrayOrDictionary isKindOfClass:NSDictionary.class]'
`

`return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));`

**Comment by ulukaya** [comment]
This is probably due to a bad database state. I'll debug and fix it now. If it persists, please create a new bug at https://github.com/firebase/friendlypix-ios/issues
