### ISSUE TITLE
Getting numerous errors after deploying site

### ISSUE THREAD

**Issue by joshua-nicholson** [firebase/friendlypix#86]
I followed the instructions in the web read me but am getting a lot of errors and am not sure why. Here are the steps I took to get the site deployed (Ubuntu):

1. Downloaded the repo and put the contents of the web folder into a folder named "Firebase".
2. Opened terminal and ran `npm install` inside the Firebase folder.
3. Ran `cd functions; npm install; cd -` in the root of the Firebase folder.
4. Replaced the comment in index.html with the code from my Firebase console.
5. Ran `npm run build`
6. Ran `firebase deploy --project <PROJECT_ID>` with my correct Project ID.
7. The deploy was successful according to terminal but I only see the splash screen of Firendly Pix and no option to sign in.

Google Chrome's console gives me the errors in the linked image below.

http://i.imgur.com/Ed0vApb.png

**Comment by nicolasgarnier** [comment]
It seems that none of the generated `.js` files are here. We generate ES5 `.js` files from the `.es6.js` files in the `./public/scripts` directory. They get generated in the `./public/scripts-es5` directory

Was there any errors when you ran `npm run build` ?

Can you run `npm run build` again and check if there is any files generated inside `./public/scripts-es5`?

**Comment by joshua-nicholson** [comment]
I don't get any error messages after running `npm run build`. Yes there are files in the `public/scripts-es5` folder, here's a screen shot.

http://i.imgur.com/4BfWJ5x.png

**Comment by nicolasgarnier** [comment]
Can you deploy (`firebase deploy`) and give me the URL ? I'll have a look there.

**Comment by joshua-nicholson** [comment]
Here you go: https://beerme-b6cd6.firebaseapp.com/

**Comment by nicolasgarnier** [comment]
OK it looks like the libraries are missing.

Normally when you run `npm run build` this runs `bower install` which install some libs such as `/libs/page/page.js` (and jquery and latinize and sweetalert). Can you check that you have `/libs/page/page.js` for instance? If not can you manually run `bower install`? if it's till not there can you check if maybe the libs got installed somewhere else.

**Comment by joshua-nicholson** [comment]
Okay so if I run `bower install` it creates a folder named `bower_components` with the correct files in it. I tried renaming this to `libs` and then deploying but I am still running into the same errors. I also tried not changing the folder name and deploying again but I still have the same errors.

**Comment by nicolasgarnier** [comment]
It needs to be inside `./public/libs` (not just `./libs`)

Normally the [.bowerrc](https://github.com/firebase/friendlypix/blob/master/web/.bowerrc) file ensures Bower will install these libs under `./public/libs`. Can you tell me which version of bower you have installed and which OS you are running?

**Comment by nicolasgarnier** [comment]
PS: I really should switch to using only NPM now :D

**Comment by joshua-nicholson** [comment]
I'm using v1.8.0 of bower and the OS I'm running is Ubuntu 16.04 LTS. Moving the lib folder into public got my site up and running though!

**Comment by joshua-nicholson** [comment]
Actually I take that back, the home page is working properly but the feed is giving the error below. Any ideas?

http://i.imgur.com/1uKpDlI.png

**Comment by nicolasgarnier** [comment]
Let's merge your new issue in #87  which looks similar...
