### ISSUE TITLE
I'm getting a an error for the feed on Web

### ISSUE THREAD

**Issue by matta174** [firebase/friendlypix#87]
I get the error
 `Uncaught (in promise) TypeError: Cannot read property 'uid' of undefined
    at friendlyPix.Post.fillPostData (post.js:126)
    at friendlyPix.Feed.addPosts (feed.js:62)
    at friendlyPix.firebase.getPosts.then.data (feed.js:134)`
when trying to view the feed on the web application.
 Home works fine as it shows every post that someone I follow or I have posted. I have followed everything to my knowledge but I can't seem to figure out what is going on.
![image](https://cloud.githubusercontent.com/assets/11731369/25031941/3b967a3e-209e-11e7-822c-75fb28303bd6.png)

**Comment by nicolasgarnier** [comment]
(sorry for the delay).
cc'ing @joshua-nicholson who had this issue on #86

It looks like the post that we want to display does not have an Author... (it should always though, it's even enforced by security rules).

Could you deploy your version of friendlypix so I could have a look? I'm not getting this issue on http://friendly-pix.com

**Comment by nicolasgarnier** [comment]
Closing since this is old and stale but feel free to re-open
