### ISSUE TITLE
Facebook profile picture now returning 403: URL signature expired

### ISSUE THREAD

**Issue by drumttocs8** [firebase/friendlypix#89]
When a user signs in via Facebook, the profile picture is generally set as their Facebook profile picture. Recently, that picture is now showing blank, and the console shows a 403 error: URL signature expired. It seems that the CDN url has expired; how do we reset this request? Would this require custom code, or is it a bug with Firebase Auth?

**Comment by NewestUser** [comment]
Same problem here. I am using the sdk for android.

**Comment by nicolasgarnier** [comment]
Hey @bojeil-google,

Looks like we might have an issue with refreshing the Facebook profile pics. I noticed the same thing on one of my apps once (was a while ago, I'm not finding the user any more...).

**Comment by bojeil-google** [comment]
Hey @nicolasgarnier I think this is a backend issue. It may be more effective to file an internal bug on this (for external developers, Official support channels are available). Firebase Auth doesn't proactively update provider data, unless you reauthenticate with the provider. My understanding is that the provider data will be updated then (`currentUser.providerData[0].photoURL`). However, the top level `currentUser.photoURL` may be stale. In that case, `currentUser.updatedProfile` is available to overwrite the stale photo.

**Comment by nicolasgarnier** [comment]
This issue was moved to firebase/friendlypix-web#21
