### ISSUE TITLE
Error while uploading new pic TypeError: "snapshot.metadata.downloadURLs is undefined"

### ISSUE THREAD

**Issue by compojoom** [firebase/friendlypix#99]
When I try to upload an image I get:
Error while uploading new pic TypeError: "snapshot.metadata.downloadURLs is undefined"

The image is being uploaded to cloud storage. I looked at the snapshot returned from .put and I  really don't have matadata.downloadURLs?

**Comment by nicolasgarnier** [comment]
Are you getting this with the latest code from the repo? There has been some non-backward compatible change where `matadata.downloadURLs` has been deprecated in favor of `snapshot.ref.getDownloadURL()`.

If you are using old code I'd upgrade. If you just puled the code out of the repo can you give me the location of the error?

**Comment by compojoom** [comment]
Hey @nicolasgarnier,
I just pulled the code from this repository yesterday & I use the samtstern-patch-1 branch. Last commit there is from April.

I've launched the site with https://www.gstatic.com/firebasejs/5.0.4/firebase.js? Is this the correct version I should be using?

Error is here:
Error while uploading new pic TypeError: "snapshot.metadata.downloadURLs is undefined"
picUploadTas khttp://localhost:5000/scripts-es5/firebase.js:436:13 firebase.js:440:6

As I said I debugged it here:
```
    var picUploadTask = picRef.put(pic, metadata).then(snapshot => {
      console.log('New pic uploaded. Size:', snapshot.totalBytes, 'bytes.');
      console.log(snapshot)
      var url = snapshot.metadata.downloadURLs[0];
      console.log('File available at', url);
      return url;
    }).catch(error => {
      console.error('Error while uploading new pic', error);
    });
```

and the snapshot is missing the downloadUrls. Problem is I also don't see a getDownloadURL() on the ref???

**Comment by nicolasgarnier** [comment]
Oh I see, the web app is now in a separate repo here: https://github.com/firebase/friendlypix-web

Not sure what `samtstern-patch-1` is for but the `master` branch here has no more code, we're only keeping this repo to have a place to hold the common architecture/design docs between iOS/Android/Web, https://github.com/firebase/friendlypix-web should work fine :)
